### ISSUE TITLE
How can I send data to UI from another thread?

### ISSUE THREAD

**Issue by anatawa12** [libui-rs/libui#16]
The `UI` struct is `!Send` so I cannot send UI and call `UI::queue_main` from threads other than main.

However, It seem `uiQueueMain` is a function that is expected to called from non-main thread to do some work in another thread and return back to main thread.

How can should I call `uiQueueMain` from threads other than main thread with this safe wrapper?

**Comment by anatawa12** [comment]
After writing my code more with unsafe and directly calling `uiQueueMain`, I found that we have to send ui parts (like `Checkbox`) between threads to work well so it might be better to more complex wrapper with thread safety like
```rust 
fn run_offthread<R>(off_thread: impl FnOnce() -> R + send, main_thread: impl FnOnce(R) -> ())

run_offthread(|| { /* heavy code*/ }, || { /* update ui */ })
```

**Comment by nptr** [comment]
Yes, `uiQueueMain` is meant to be called from other threads, so that you can perform UI operations on the main (=UI) thread where they must run. As you correctly indicate in your example, that would usually be just the update portion, not the full workload.

Unfortunately I am kinda limited with my time and also not proficient enough with Rust to properly express this functionality.
If you happen to find a working solution, I'd gladly accept a merge request.
