### ISSUE TITLE
Evaluating libui functionality

### ISSUE THREAD

**Issue by npwoods** [libui-rs/libui#5]
I'm reviewing `libui` and trying to get my head wrapped around its supported functionality.  Can someone confirm the following findings:
* Multiple levels of menu hierarchy is not supported
* Renaming menu items "on the fly" is not supported
* Hiding and showing menu items "on the fly" is not supported
* There is no simple "picture control" that would let me place an arbitrary image (say a PNG icon) on my layout.  While this probably could be done with an `Area` this feels unwieldy.

Being a veteran Win32 developer, I suspect it would be quite easy for me to extend `libui` to support this functionality, but the other platforms would almost certainly be an issue.

I don't need something as heavyweight as Qt so the "keep it simple" approach of `libui` does appeal to me, so I want to make sure I'm giving `libui` a fair evaluation.

**Comment by nptr** [comment]
Thanks for reaching out. Functionality wise libui (the native [libui-ng](https://github.com/libui-ng/libui-ng) actually, behind libui-rs) indeed only provides a minimum due to it having to find a common denominator across the platforms and the effort of having to implement something on three platforms. To answer your questions to best of my knowledge:

> Multiple levels of menu hierarchy is not supported

That is true.

>Renaming menu items "on the fly" is not supported

That is true.

>Hiding and showing menu items "on the fly" is not supported

You can disable/and enable them with `MenuItem::disable()`, but indeed not hide/show.
https://docs.rs/libui/latest/libui/menus/struct.MenuItem.html#method.disable

>There is no simple "picture control" that would let me place an arbitrary image (say a PNG icon) on my layout. While this probably could be done with an Area this feels unwieldy.

That is unfortunately correct, afaik.

PS: The guys working on [libui-ng](https://github.com/libui-ng/libui-ng) would surely appreciate your skills - even if its just pieces of code or Win32 API advice.

**Comment by npwoods** [comment]
Thank you for the info.  Taking a closer look at `libui-ng` it seems that it is the "dore" project and `libui-rs` are really just Rust bindings onto it (correct me if I'm wrong!).  I found `libui` by looking for Rust GUI libraries so I came to it through the Rust angle.

Again, thanks!

**Comment by nptr** [comment]
Happy to help. Yes, libui-rs is a wrapper over libui-ng. Both are actually continuations of [older and now abandoned projects](https://github.com/libui-rs/libui#acknowledgments). Don't know what "dore" means though. 

If you sacrifice either nativeness or cross platform compatibility you'll find Rust libraries or API bindings with more features, but with both I don't think there isn't much better choices around unfortunately :( Maybe there are wxWidgets bindings that are good, I can't remember.

**Comment by npwoods** [comment]
Ugh I meant "core", not "dore".  Thanks!
